[ -n "$PS1" ] && source ~/.bash_profile

export NVM_DIR="$HOME/.nvm"

export VISUAL=nvim
export EDITOR="$VISUAL"

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
