#!/bin/bash

# Lock screen.
alias afk="gnome-screensaver-command --lock"

# Shorter commands for the `Advanced Packaging Tool`
alias apti="sudo apt-get install"
alias aptr="sudo apt-get remove"
alias apts="sudo apt-cache search"
alias aptu="sudo apt-get update \
                && sudo apt-get upgrade"

# Empty trash.
alias empty-trash="rm -rf ~/.local/share/Trash/files/*"

# Hide/Show desktop icons.
alias hide-desktop-icons="gsettings set org.gnome.desktop.background show-desktop-icons false"
alias show-desktop-icons="gsettings set org.gnome.desktop.background show-desktop-icons true"

# Update applications and CLTs.
alias u="sudo apt-get update \
            && sudo apt-get upgrade \
            && npm install -g npm \
            && npm upgrade -g"

# Restart Network Conections (Wifi)
alias restartwifi="sudo service network-manager restart"
alias connectvpn="nmcli con up id VPN\ IR"
###
