-- local status, catppuccin = pcall(require, "catppuccin")
-- if (not status) then return end

-- catppuccin.setup({
--     flavour = "mocha", -- latte, frappe, macchiato, mocha
--     background = { -- :h background
--         light = "latte",
--         dark = "mocha",
--     },
--     transparent_background = false, -- disables setting the background color.
--     show_end_of_buffer = false, -- shows the '~' characters after the end of buffers
--     term_colors = false, -- sets terminal colors (e.g. `g:terminal_color_0`)
--     dim_inactive = {
--         enabled = true, -- dims the background color of inactive window
--         shade = "dark",
--         percentage = 0.15, -- percentage of the shade to apply to the inactive window
--     },
--     no_italic = false, -- Force no italic
--     no_bold = false, -- Force no bold
--     no_underline = false, -- Force no underline
--     styles = { -- Handles the styles of general hi groups (see `:h highlight-args`):
--         comments = { "italic" }, -- Change the style of comments
--         conditionals = { "italic" },
--         loops = {},
--         functions = {},
--         keywords = {},
--         strings = {},
--         variables = {},
--         numbers = {},
--         booleans = {},
--         properties = {},
--         types = {},
--         operators = {},
--     },
--     color_overrides = {
--       mocha = {
--         base = "#080808",
--         mantle = "#000000",
--         crust = "#000000",
--       },
--     },
--     custom_highlights = {},
--     integrations = {
--         cmp = true,
--         gitsigns = true,
--         coc_nvim = true,
--         treesitter = true,
--     },
-- })

-- -- setup must be called before loading
-- vim.cmd.colorscheme "catppuccin-mocha"
